### PR TITLE
Fix expansion of `__VA_ARGS__` macro argument in MSVC

### PR DESCRIPTION
**Pull request by samangh**
This merge request fixes issues with variadic macro argument expansion in MSVC. The issue is that when passing  `__VA_ARGS__`  as an argument to another macro, MSVC expands `__VA_ARGS__` after passing, whilst gcc expands it before.

Issue #31 can be closed.

### CODE REVIEW

**Comment by samangh** [comment]
~~Note: you still need to reduce the number of macro arguments to < 127 for this to work in MSVC. I haven't changed that as @quicknir seems to have settled on using 258 as the default.~~

~~@quicknir: how do you feel about reducing the default number of macro argyments to 125, so that the appveyor CI tests get passed.~~

**Comment by samangh** [comment]
@quicknir: I noticed that in the 'dev' branch you are are already looking at reducing the max number of iterations, so I've also done that in this pull request. Of course, feel free to ignore.

Although this merge request works find on my simple use scenario using C++17, I see that it's still failing the C++14 appveyor tests. Looks like some further debugging will be required ... .

**Comment by quicknir** [comment]
@samangh the reduction in iterations is only to support MSVC, so if that is not necessary to support MSVC, it's fine to leave it at 256. This looks quite promising; even if there are still some issues with MSVC, if this doesn't break Linux (which it seems unlikely to do), I can still merge what we have, as it seems a step in the right direction.

Out of curiosity, do you know whether it's MSVC or gcc that's compliant in terms of the macro expansion order? IIRC variadic macros were officially standardized in C++11 so there should be some wording on this.

**Comment by samangh** [comment]
@quicknir: Yeah, unfortunately the 125 max iterations is a hard compiler limit in MSVC.

I'm not sure about which of the two compilers is more compliant. I suspect that the expansion order is not specified clearly in the standard (although I haven't checked), see the replies to this [stackoverflow question](https://stackoverflow.com/questions/5134523/msvc-doesnt-expand-va-args-correctly) for instance.

**Comment by samangh** [comment]
Looks like I managed to fix all the issues, so this can be merged.

I also made `test/CMakeLists.txt` more platform agnostic. We now only check with Visual Studio 2019, as only VS2019 is installed in the appveyor build image.

**Comment by samangh** [comment]
@quicknir: I was wondering if you've had any chance to look at this? Much appreciated.

**Comment by quicknir** [comment]
Hey sorry! I lost track of this, glad you pinged me. All looks good, merging. Thanks very much for your help.

**Comment by samangh** [comment]
@quicknir: No problem. Glad to see that you were happy with the changes :-). If you get a chance, could you also look at merge request #27?

Thanks for your work on wise_enum!

**Pull request merged**
