### PR TITLE
Feature/travis unit test

### PR DESCRIPTION
**Pull request by JonasProgrammer**
First implementation for #16. Horribly ugly, but it does the job for now

### CODE REVIEW

**Comment by quicknir** [comment]
It looks like your branch here has 3 commits, 2 of which were already merged, and for that reason there are conflicts. Can you rebase your branch, so that it's just the one commit? Also, is it possible to add windows to the matrix? Sorry I was slow responding to this.

**Comment by JonasProgrammer** [comment]
I don't know what exactly I did, but I somehow managed to screw up my branching so much I had to start from scratch and cherry-pick the good stuff. Anyways, it should be fixed now.

Regarding windows: I did a quick skimming and apparently travis does support it by now, but I have absolutely no clue how it is set up or how to deal with potential OS differences in terms of shell commands for the install script.
That being said, AppVeyor seems to be more mature when it comes to OSS CI in Windows. I have no clue how to set it up properly though.

IMHO, matrix-testing gcc and clang (with 2 different standard lib implementations) on Linux should be sufficient, as far as it comes for those two compilers. If they did behave differently on Windows, I'd consider it a compiler/implementation bug.
I do agree that Visual Studio should be added to the compilers under test, but as stated before, I think that's a separate thing for AppVeyor.

**Comment by quicknir** [comment]
Well, as it happens, the library currently doesn't compile for MSVC because macros are limited to only 127 arguments, which is actually conformant (if annoying). So I was hoping to get some CI for windows. However, this is a good start. One possibly-easier followup that would be nice to address would be to also add support for 11. Again, I made a small mistake and since I'm not compiling 11 locally these things tend to get through (Murphy's Law).

Thanks for your contribution!

**Comment by quicknir** [comment]
Closes #16 .

**Pull request merged**
